 
import ServiceSection from "~/components/Section/Service/ServiceSection";
import HeaderFour from '~/components/Section/Common/Header/HeaderFour';
import FooterFour from '~/components/Section/Common/FooterFour';

const TermsAndCondition = () => { 
    
    return ( 
        <div>
            <HeaderFour />  
                    <title>Politicas de privacidade</title>
               <div className="section tekup-section-padding">
                   <div className="container">
                          <br/> <br/> 
                          <div><p><strong className="txt-blue">1. COMPROMISSO</strong></p>
                          <p>A proteção da privacidade dos utilizadores e dos seus dados pessoais constitui um compromisso fundamental da Waveled.</p><p> A Waveled aconselha a leitura da presente Política de Privacidade.</p><p>Esta Política de Privacidade foi redigida de forma clara e simples, para facilitar a sua compreensão, e decidir de forma 
                            livre e voluntaria se pretende facultar os seus dados pessoais e explica quais são os dados pessoais que a Waveled 
                            recolhe através das interações consigo e como esses dados são utilizados. </p><br/><p><strong className="txt-blue">2. ÂMBITO DE APLICAÇÃO, RESPONSÁVEL PELO TRATAMENTO DE DADOS E ENCARREGADO DA PROTEÇÃO DE DADOS</strong></p><p>A presente Política de Privacidade aplica-se aos dados pessoais dos nossos utilizadores, clientes, fornecedores, candidatos e demais stakeholders.</p><p>O responsável pela recolha e tratamento dos seus dados pessoais são as empresas da Waveled que lhe fornecessem produtos e/ou serviços e que nesse âmbito decide quais os dados recolhidos, meios de tratamento e finalidades para que os dados são usados.</p><p>A Waveled nomeou um Encarregado da Proteção de Dados (Data Protection Officer ou DPO), que monitoriza a conformidade do tratamento de dados com as normas aplicáveis,
                            é um ponto de contacto com o utilizador para esclarecimento de questões relativas ao tratamento dos seus dados, coopera com as autoridades de controlo e presta informação e aconselha o responsável pelo tratamento ou o subcontratante sobre as suas obrigações no âmbito da privacidade e proteção de dados.</p><br/><p><strong className="txt-blue">3. DADOS PESSOAIS, TITULARES DE DADOS PESSOAIS E CATEGORIAS DE DADOS PESSOAIS</strong></p><p>«Dados Pessoais», refere-se à informação relativa a uma pessoa singular identificada ou identificável («Titular dos Dados»); é considerada identificável uma pessoa singular que possa ser identificada, direta ou indiretamente, em especial por referência a um identificador, como por exemplo um nome, um número de identificação, dados de localização, identificadores por via eletrónica ou a um ou mais 
                            elementos específicos da identidade física, fisiológica, genética, mental, económica, cultural ou social dessa pessoa singular;</p><p>«Titular dos Dados» é a pessoa singular, a quem os dados dizem respeito;</p><p>Esta Política permite-lhe saber como a Waveled recolhe e usa os seus Dados Pessoais, como pode controlar o seu uso e descreve as nossas práticas em relação a informação recolhida em todos os sites (incluindo mas não limitando, aplicações de software, redes sociais e mensagens eletrónicas) da Waveled, bem como, atividades de marketing e de vendas offline (coletivamente, “Canais de Comunicação”). Os Canais de Comunicação podem providenciar links para outras plataformas não pertencentes à Waveled. Encorajámo-lo a verificar as políticas de privacidade desses websites, serviços, redes sociais ou aplicações antes de fornecer os seus Dados Pessoais, sendo que, não somos responsáveis pelo tratamento dos dados pessoais que eventualmente sejam fornecidos e/ou recolhidos nos mesmos.</p><br/><p><strong className="txt-blue">3.1. QUANDO E QUAL A INFORMAÇÃO RECOLHEMOS SOBRE SI? </strong></p><p>Recolhemos os seus dados pessoais, com o seu consentimento, quando se regista no nosso website ou coloca um pedido de aquisição de produtos ou serviços. Nós também recolhemos os seus dados pessoais quando voluntariamente preenche questionários, formulários ou usa ferramentas de conversação.</p><p>Pedimos-lhe que não envie ou partilhe com a Waveled qualquer informação pessoal sensível como a origem racial ou étnica, as opiniões políticas, as convicções religiosas ou filosóficas, ou a filiação sindical, bem como dados genéticos, dados biométricos, dados relativos à saúde ou dados relativos à vida ou orientação sexual.</p><p>A informação de uso do website é recolhida usando cookies, mas não o identificam especificamente, sendo ou podendo ser recolhidos os dados seguintes:</p><p>Endereço IP.</p><p>Localização geográfica.</p><p>Informação acerca do dispositivo que está a aceder ao website, nomeadamente, tipo e versão do navegador, sistema operativo, resolução do ecrã, linguagem preferida, informação contida nos cabeçalhos HTTP e versão do agente.</p><p>O motor de busca que usou para localizar e aceder ao website.</p><p>Data e tempo de atividade no website, bem como, páginas web e conteúdos visitados e clicados.</p>
                            <p>Importa realçar que esta informação de uso não o identifica deliberadamente. e se excecionalmente (o identificar a mesma será anonimizada de imediato.</p><p>Ao ceder informação está a dar o seu consentimento informado e inequívoco de que consente o tratamento dos dados que lhe digam respeito de forma automatizada., O referido consentimento prévio e expresso do titular dos dados será dado por escrito, oralmente ou através da validação de uma opção.</p><p>Alguns dos dados solicitados são de carater obrigatório e encontram-se devidamente assinalados, podendo a falta ou inexatidão das respostas dadas comprometer o serviço prestado.</p><br/><p><strong className="txt-blue">3.2. DE QUE FORMA USAMOS A INFORMAÇÃO SOBRE SI?</strong></p><p>Os dados recolhidos servem para processar o seu pedido, gerir a sua conta e, se concordar, enviar-lhe por correio eletrónico informação acerca de outros produtos e serviços.</p><p>Usamos a informação recolhida do website para personalizar as suas próximas visitas ao nosso website.</p><p>Se concordar iremos enviar a sua informação pessoal às diversas empresas da Waveled para que lhe possam oferecer os seus produtos e serviços. </p><p>A Waveled não partilha a sua informação para campanhas de marketing com empresas não pertencentes ao grupo nem transfere os seus Dados Pessoais para um país terceiro.</p><p>Embora a informação fornecida seja geralmente tratada como privada na Waveled, os dados recolhidos serão utilizados em conformidade com o regulamento de proteção de dados pessoais, durante todo o processo 
                            de tratamento; pode, no entanto, ser necessário transferir Dados Pessoais de forma privada para outros órgãos, nomeadamente, o judicial, e/ou usar informação de agências/seguradoras de crédito ou semelhantes.</p><p>Tem o direito de apresentar reclamação a uma Autoridade de Controlo Nacional e/ou da União Europeia em relação a qualquer violação dos seus Dados Pessoais. 
                            A Waveled prestará a sua colaboração à Autoridade de Controlo facultando-lhe todas as informações que por esta, no exercício das suas competências, lhe forem solicitadas. </p><p> A Waveled só aceita registos de utilizadores com pelo menos 16 anos de idade. Os Canais de Comunicação da Waveled não são direcionados
                            a utilizadores menores de idade. Se souber de algum registo efetuado por um menor agradecemos que nos alerte, a fim de procedermos de imediato à remoção do registo do mesmo. </p><p>Os destinatários ou categorias de destinatários dos seus Dados Pessoais, dependendo da ferramenta de contacto que utilizar são os departamentos que intervêm na relação comercial, 
                            os departamentos de Marketing, a Direção de Pessoas, e demais departamentos das diferentes empresas da Waveled.</p><p>Sempre que transferir ou descarregar um pacote de software em qualquer website de qualquer empresa da Waveled, poderá ser contacto com os objetivos
                            de acompanhar a experiência de utilização e de apresentação do software em causa e/ou de outros produtos semelhantes.</p><p>Decisões Automatizadas: </p><p>A informação recolhida nos websites da Waveled não envolve a tomada de decisões automatizadas, incluindo a definição de perfis.  </p><p>Os seus dados poderão circular em rede aberta correm o risco de serem vistos e utilizados por terceiros não autorizados.</p><p>Nos websites da Waveled não são efetuadas comparações, interconexões ou qualquer outra forma de inter-relacionar as informações registadas. </p><br/><p><strong className="txt-blue">3.3. MARKETING</strong></p><p>Gostaríamos de lhe poder enviar informação acerca dos produtos e serviços das empresas da Waveled que possam ser ou vir a ser do seu interesse. Se deu 
                            o seu consentimento anteriormente pode sempre optar por cancelar a subscrição. Tem o direito em qualquer altura de não 
                            permitir que seja contactado para campanhas de marketing. </p><br/><p><strong className="txt-blue">3.4. CONDIÇÕES GERAIS DE FORNECIMENTO</strong></p><p>As Condições gerais de fornecimento da Waveled encontram-se disponíveis nos websites da Waveled.</p><br/><p><strong className="txt-blue">3.5. TRANSMISSÃO DE DADOS PESSOAIS</strong></p><p>Os seus dados podem ser transmitidos empresas subcontratadas para que estas os tratem em nome e por conta das empresas da Waveled.</p><p>As entidades subcontratadas, bem como as entidades fornecedoras ou licenciadores de serviços às empresas da Waveled, poderão ter acesso a dados recolhidos e registados pelas empresas da Waveled, quando e na medida em que tal se mostre necessário 
                            para a oferta ao Cliente de produtos ou serviços comercializados pelas empresas da Waveled, ou para o cumprimento das obrigações contratuais estabelecidas entre as empresas da Waveled e o Cliente.</p><br/><p><strong className="txt-blue">3.6. RECRUTAMENTO E SELEÇÃO</strong></p><p>Ao submeter uma candidatura espontânea ou candidatura a uma oportunidade, autoriza que os seus dados pessoais recolhidos sejam processados e armazenados informaticamente pela Waveled com a 
                            finalidade de poder vir a ser contactado para processos de recrutamento e seleção em aberto, ou que possam surgir no futuro, para as empresas da Waveled.</p><p>Os seus dados pessoais são conservados durante 2 anos após os quais são eliminados. Deverá submeter nova candidatura após este período caso queira continuar a constar na Base de Dados da Waveled.</p><p>Caso seja integrado num processo de recrutamento e seleção, esse processo será mantido durante 5 anos.</p><p>Os destinatários ou categorias de destinatários dos seus dados pessoais são a Direção de Pessoas, a Administração, e outras Direções ou funções relevantes para a análise da candidatura.</p><p>Os seus dados pessoais também podem ser partilhados com outras entidades quando exigido por lei ou para responder a um processo legal, e ainda em situações que impliquem a proteção de clientes, a proteção de vidas, a segurança dos serviços, a proteção dos direitos de propriedade ou as empresas da Waveled.</p><p>Os processos de recrutamento não envolvem a tomada de decisões automatizadas, incluindo a definição de perfis.</p><p>Não são realizadas comparações, interconexões ou qualquer outra forma de inter-relacionar as informações registadas.</p><p>Carece de consentimento o tratamento posterior dos dados pessoais para um fim que não seja aquele para o qual os dados tenham sido recolhidos.</p><p>A Waveled só aceita candidaturas de pessoas com pelo menos 16 anos, que tenham concluído a escolaridade obrigatória e que disponham de capacidades físicas e psíquicas adequadas ao posto de trabalho.</p><br/><p><strong className="txt-blue">3.7. ÉTICA </strong></p><p>O código de ética da Waveled estabelece os valores e princípios éticos de atuação da Waveled e
                            como eles se devem refletir nas nossas relações com as diferentes partes interessadas.</p><p>Para denunciar as más práticas éticas, deve consentir com o tratamento dos seus dados pessoais, para esse efeito e como forma de salvaguardar os 
                            riscos de denúncias caluniosas e de discriminação. A ausência de consentimento determina o não tratamento da comunicação e a sua eliminação e dos dados nela contidos.</p><p>Os seus dados pessoais serão eliminados imediatamente se se revelarem imprecisos ou inúteis; serão armazenados durante 6 meses após o fim das investigações se não houver processo disciplinar ou judicial e até ao fim do 
                            processo se houver processo disciplinar ou judicial. Nesse caso, seus dados pessoais ficarão armazenados num sistema de informação de acesso restrito por um período não superior ao processo disciplinar ou judicial.</p><p>Os seus dados pessoais também podem ser partilhados com outras entidades quando exigido por lei ou para responder a processos judiciais, e também em situações que envolvam a proteção de clientes, proteção de vidas, segurança de serviços, proteção de direitos de propriedade ou empresas da Waveled .</p><p>Os processos de recrutamento não envolvem tomada de decisão automatizada, incluindo a definição de perfis. Não são feitas comparações, interconexões ou qualquer outra forma de inter-relacionamento das informações registadas.</p><br/><p><strong className="txt-blue">4. PRAZOS E FUNDAMENTOS DE TRATAMENTO E CONSERVAÇÃO DE DADOS PESSOAIS</strong></p><p>Sem prejuízo de disposições legais ou regulamentares em contrário, os Dados Pessoais serão conservados/tratados apenas pelo
                            período mínimo necessário para as finalidades que motivaram a sua recolha ou o seu posterior tratamento.</p><p>Carece de consentimento o tratamento posterior dos Dados Pessoais para um fim que não seja aquele para o qual os dados tenham sido recolhidos, antes desse tratamento as empresas da
                            Waveled, solicitam o respetivo consentimento e fornecem ao Cliente informações sobre esse fim e quaisquer outras informações pertinentes.</p><p>A Waveled irá manter os seus dados pessoais pelo período de tempo no qual mantiver se mantiver a relação contratual estabelecida com o titular dos dados pessoais.</p><p>Há casos em que a lei obriga ao tratamento e conservação dos dados por um período de tempo mínimo.</p><p>Na falta de obrigação legal específica, então os dados serão tratados/conservados apenas pelo período de tempo necessário para o cumprimento das finalidades que motivaram a sua recolha e preservação ou, 
                            consoante o que for aplicável, até que exerça o seu direito de oposição, direito a ser esquecido ou retire o consentimento e sempre de acordo com a lei, as orientações e decisões das autoridades de controlo.</p><p>É assegurado ao Cliente, nos termos legais, o direito de retirar o seu consentimento em qualquer altura, sem comprometer a licitude do tratamento efetuado com base no consentimento previamente dado e o direito de solicitar às empresas da Waveled acesso aos Dados Pessoais que lhe digam respeito, bem como a sua retificação 
                            ou o seu apagamento, e a limitação do tratamento no que disser respeito ao Cliente, ou do direito de se opor ao tratamento, bem como do direito à portabilidade dos dados mediante comunicação escrita dirigida a Waveled.</p><p>Os Dados Pessoais necessários para a execução do contrato no qual o Cliente é parte, para o cumprimento das obrigações jurídicas a que o Responsável pelo Tratamento esteja sujeito e os que sejam necessários para efeito dos interesses legítimos prosseguidos pelas empresas da Waveled não estão incluídos no ponto anterior.</p><p>Decorrido o período de conservação/tratamento, a Waveled eliminará ou, caso seja do interesse das empresas da Waveled, anonimizará (de tal modo que o Cliente não seja ou já não possa ser identificado) os dados sempre que os mesmos não devam ser conservados para finalidade distinta que possa subsistir.</p>
                            <br/>
                            <p>
                            <strong className="txt-blue">4.1. FUNDAMENTOS PARA O TRATAMENTO DE DADOS PESSOAIS</strong></p>
                            <p>Consentimento: quando tiver o consentimento prévio e expresso do titular dos dados – por escrito, oralmente ou através da validação de uma opção – e se esse consentimento for livre, informado, específico e inequívoco.</p><p>– caso especial dos menores:</p><p>No caso de tratamento de dados pessoais de menores, que possam estar sujeitos a consentimento prévio, a o mesmo deverá ser prestado por parte dos titulares das responsabilidades parentais.</p><p>Execução de contrato: quando o tratamento de dados pessoais seja necessário para a celebração, execução e gestão do contrato celebrado com qualquer das empresas da Waveled.</p> <p>Cumprimento de obrigação legal: quando o tratamento de dados pessoais seja necessário para cumprir uma obrigação legal a que a Waveled esteja sujeito.</p><p>Interesse legítimo: quando o tratamento de dados pessoais corresponda a um interesse legítimo da Waveled ou de terceiros.</p><br/><p><strong className="txt-blue">5. COOKIES</strong></p><p>A Waveled utiliza cookies em todos os nossos sites para melhorar o desempenho e a sua experiência como utilizador.</p><p>A utilização de cookies pela Waveled tem os objetivos de analisar o uso do website e permitir-lhe ter uma experiência de navegação sem problemas; em momento algum recolhemos Dados Pessoais através de cookies.</p><p>Os cookies não serão usados para nenhum outro propósito dos mencionados no ponto anterior.</p><p>Cookies são pequenos ficheiros de texto que um site, ao ser visitado pelo utilizador, coloca no seu computador ou no seu dispositivo móvel através do navegador de internet (browser). Esta informação é usada para registar o número de visitas efetuadas e compilar informação estatística acerca da atividade do website.</p><p>Usamos o termo cookies nesta Política para referir todos os ficheiros que recolhem informações desta forma.</p><p>Tipos de Cookies consoante a entidade que os gere:</p><p>Cookies próprios: um cookie gerido por este domínio / website.</p><p>Cookies de terceiros: um cookie gerido por outro domínio / website.</p><p>Cookies persistentes: a informação do cookie encontra-se armazenada de forma permanente no seu equipamento.</p><p>Cookies próprios: um cookie gerido por este domínio / website.</p><p>Cookies de terceiros: um cookie gerido por outro domínio / website.</p><p>Cookies persistentes: a informação do cookie encontra-se armazenada de forma permanente no seu equipamento.</p><br/></div>
                     </div>
                </div> 
            <FooterFour />
        </div> 
    );
};

export default TermsAndCondition ; 